### ISSUE TITLE
关于脚注(footnotes)的id出现问题的那回事

### ISSUE THREAD

**Issue by TNXG** [Innei/Shiro#141]
### Describe the bug

脚注形成的`[^1]`，其id是`fnref:1`，尾部footnotes返回正文所用的id是`footnote-ref-1`导致定位出错（

### Reproduction

None

### System Info

```Shell
Problems with pages rendering
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
Maybe fixed?
