### ISSUE TITLE
OpenAI API Proxy Support / Copy link not work / Inline LaTeX need space

### ISSUE THREAD

**Issue by zhuozhiyongde** [Innei/Shiro#156]
### Clear and concise description of the problem

如题，现有的 AI 总结似乎并不支持配置代理。这在国内环境显然是不能使用的。

另外，Copyright 组件中的复制失效了：

<img width="426" alt="Cleanshot-2023-11-13-at-11 24 55@2x" src="https://github.com/Innei/Shiro/assets/36695271/2ada76d7-3587-44d3-9a20-2dffceef94c0">

（在 innei.in 下同样不可用）

最后是，现有的 Inline LaTeX 要求在美元符号和内容之间有个空格，但这会导致同样的 markdown 在 Github 上无法解析，所以希望大佬能够修一下这个特性。

如下：

$ abc $

### Suggested solution

增添 Proxy 配置。

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
我并没有做去 OpenAI 的东西
