### ISSUE TITLE
浅色模式下滚动条颜色辨析不清

### ISSUE THREAD

**Issue by zhuozhiyongde** [Innei/Shiro#185]
### Describe the bug

![Cleanshot-2023-12-12-at-23 53 35@2x](https://github.com/Innei/Shiro/assets/36695271/e4068681-8bde-467f-b0b7-a3d69b75b361)

如题，完全是纯白

### Reproduction

No need.

### System Info

```Shell
No need.
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
Fixed, 3Q

**Comment by zhuozhiyongde** [comment]
感谢群主~

**Comment by zhuozhiyongde** [comment]
![Cleanshot-2023-12-13-at-22 12 46@2x](https://github.com/Innei/Shiro/assets/36695271/c77317a4-f8a7-476c-8901-6cbf9024eeb4)

@Innei 

草，现在修完了黑暗模式下又变得离谱起来了（逃

**Comment by zhuozhiyongde** [comment]
Update：页面右侧的滚动条也变了

![Cleanshot-2023-12-13-at-23 26 13@2x](https://github.com/Innei/Shiro/assets/36695271/d121dff4-9b2e-4d26-aaf0-0b4ae2067066)

我想或许是导轨的 css 选择器问题？
