### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'config')

### ISSUE THREAD

**Issue by fisheryv** [Innei/Shiro#196]
### Describe the bug

When I built the project with `pnpm i`, `pnpm build`, I got errors below: 

```
TypeError: Cannot read properties of null (reading 'config')
    at Module.tN (/home/ubuntu/Shiro/.next/server/chunks/5542.js:9:20886)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Reproduction

1. clone code; 2. modify .env.template; 3. pnpm i; 4. pnpm build

### System Info

```Shell
System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
    Memory: 2.25 GB / 7.76 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.10.0/bin/yarn
    npm: 10.2.5 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.12.1 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
More information needed
