### ISSUE TITLE
LaTeX 公式块无法渲染

### ISSUE THREAD

**Issue by zhuozhiyongde** [Innei/Shiro#198]
### Describe the bug

如题，形如

```md
$$

P\left(U,T\right)=100\left.\left(0.6\min\left(1,\frac{U-0.70}{0.90-0.70}\right)+0.4\min\left(1,\frac{T-4000}{14000-4000}\right)\right)\right.

$$

```

这种 LaTeX 语法块无法正常渲染

### Reproduction

见描述

### System Info

```Shell
No need.
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
块级的还没做..

**Comment by zhuozhiyongde** [comment]
> 块级的还没做..

阿哲，我还以为是解析出错了（

**Comment by Innei** [comment]
PR welcome

**Comment by Innei** [comment]
Support
