### ISSUE TITLE
请教一下如何部署到自己的VPS

### ISSUE THREAD

**Issue by Valkierja** [Innei/Shiro#204]
### Describe the bug

这边不太了解nodejs相关的前后端开发, 请问一下就是我现在已经成功通过https://github.com/mx-space/docker 完成了后端的docker安装, 请问一下前端也可以部署到同一个服务器上吗, 因为我看了一下文档好像只有托管平台相关教程。谢谢~

### Reproduction

always

### System Info

```Shell
Debian11
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
是的，建议部署到 vercel

**Comment by Valkierja** [comment]
> 是的，建议部署到 vercel

好的~ 谢谢

**Comment by Valkierja** [comment]
您好， 不好意思再打扰一下请教一个小问题
就是我们部署完服务器上的docker后端， 和Vercel的前端之后
同时成功配置了Vercel的参数，从而让Vercel知道了后端的API地址
但是在访问域名时，数据包会直接发送到docker后端的服务器上（由于DNS解析到了服务器）
那么我们后端中间件处理完请求之后，是如何感知到Vercel前端的存在的呢
看了一下nginx反代配置文件里面好像也没有哪里提到了与Vercel的通信
也就是说，似乎Vercel可以知道后端的API，但是似乎后端的服务器并不能感知到Vercel的存在，而DNS解析结果似乎只会让数据包发往后端服务器，那么为什么访问的response可以包含前端渲染结果呢，请问后端是如何感知到前端存在的
可能上述内容中，错误比较多，还请不吝赐教，谢谢！

**Comment by Innei** [comment]
不是很明白你说的意思？

**Comment by Valkierja** [comment]
不好意思， 我这边重新梳理了一下思路，目前已经大致搞明白了，thanks for your time~
