### ISSUE TITLE
站点Feed加载报错

### ISSUE THREAD

**Issue by yzsong06** [Innei/Shiro#209]
### Describe the bug

链接：https://sotkg.link/feed  
前端Shrio部署环境：Vercel，前端使用Cloudflare CDN  
报错图片：
![chrome_screenshot_2023年12月26日 GMT+08_00 下午9_06_46](https://github.com/Innei/Shiro/assets/96452465/b70fe86c-d338-4f20-9c92-da1c3df07d96)

### Reproduction

Reproduction

### System Info

![1](https://github.com/Innei/Shiro/assets/96452465/844d5ab4-6788-4d22-88aa-46c4a173b718)

### Used Package Manager

Docker

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
Maybe fixed.

**Comment by yzsong06** [comment]
![chrome_screenshot_2023年12月27日 GMT+08_00 上午8_14_36](https://github.com/Innei/Shiro/assets/96452465/d7a6e622-fd4c-4dde-a337-39eae0152942)
Deployment Failed
