### ISSUE TITLE
[Feature Request] 评论交互逻辑优化

### ISSUE THREAD

**Issue by zhuozhiyongde** [Innei/Shiro#216]
### Clear and concise description of the problem

希望能够支持如下有关评论的交互逻辑改进：

* 每次换行默认换两行（同 Typora），现有的换 1 行会导致渲染多行文字在同一段内（换行被忽视），这可能不是大多数情况下的期望行为
* 支持评论编辑功能，包括博主编辑与用户编辑（然而这似乎涉及 Core 那边数据库的一些东西？）

以上，感谢大佬！

### Suggested solution

如题。

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
PR welcome

**Comment by Innei** [comment]
评论编辑功能在 赞助版中支持
