### ISSUE TITLE
点击导航栏进入折腾页面，跳转至 error page

### ISSUE THREAD

**Issue by chaseFunny** [Innei/Shiro#220]
### Describe the bug

当我第一次进入网站，然后点击导航栏，进入折腾页面，就出现了这个，并且当我点击 try again 依然无效，
并且在我之前使用 next.js 13 开发个人网站也有这种情况，本地不会出现，部署到线上就会出现，
辛苦 inner 大佬看下，感谢🙏

<img width="1051" alt="image" src="https://github.com/Innei/Shiro/assets/75657636/34cedd9d-e0c5-4612-817a-fae1434f7495">

### Reproduction

在线网站链接：https://innei.in/categories/Z-Turn

### System Info

```Shell
本人电脑 M2 max，chrome 游览器
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
感谢反馈，已在 e9935f0fafd855a90e494c627c294fdec767e153 修复
