### ISSUE TITLE
Sign in Dialog 无法交互

### ISSUE THREAD

**Issue by XBIsland** [Innei/Shiro#226]
### Describe the bug

页面弹出 dialog 时，`body` 样式会加上 `pointer-events: none;`，此时其他 dialog 继承这属性导致无法进行交互。
如下图所示，点击 *引用评论* 后再点击 *登陆后才可留言* ，此时登录弹窗无法交互。
![image](https://github.com/Innei/Shiro/assets/36447895/6900c1ab-643c-404d-ae4e-cdcae1e346cc)

### Reproduction

1. 选中文字 2.点击引用评论 3. 点击登陆后才可留言

### System Info

```Shell
Chrome: 120.0.6099.129
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
fixed in #7209233, but this is a clerk bug
