### ISSUE TITLE
编辑器

### ISSUE THREAD

**Issue by Innei** [Innei/Shiro#235]

**Comment by Innei** [comment]
![image](https://github.com/Innei/Shiro/assets/41265413/c04ea3da-0131-4d93-bd66-f971e0018c9b)

画板支持

**Comment by Innei** [comment]
支持图片上传：

https://github.com/Innei/Shiro/assets/41265413/63792618-6f60-4151-b4ae-e7e5515dd9e6

**Comment by Innei** [comment]
代码高亮编辑器内嵌

https://github.com/Innei/Shiro/assets/41265413/c53330e8-5b57-4be1-8cae-51efc4008bf1

**Comment by Innei** [comment]
[Mermaid](https://mermaid.live/) 支持

https://github.com/Innei/Shiro/assets/41265413/97a4d993-408f-4ceb-8138-bb6c6649c516

**Comment by fjhdream** [comment]
About the editor, can I help? I'm currently learning NextJS.

**Comment by Innei** [comment]
暂时不需要了，目前没有计划继续维护了。Markdown WYSIWYG 编辑器存在很多问题，显然不是一个正确的选择。

如果你愿意推进，欢迎。

**Comment by 794681962** [comment]
这么编辑器在哪有啊

**Comment by 794681962** [comment]
写文章的时候没有看到有编辑器
