### ISSUE TITLE
[Bug] Markdown 解析错误

### ISSUE THREAD

**Issue by zhuozhiyongde** [Innei/Shiro#240]
### Describe the bug

如题。

使用如下内容加以渲染：

```md
2. 在每个 phase 里检验是否输入了正确的密码，如果输入错误则调用 `explode_bomb` 函数，打印 `BOOM!!!`，并在其中调用 `send_msg` 函数，向服务器发送通知

    ```asm

    ```

    我们的代码，通过在 `call   1fb1 <send_msg>` 这一句处设置断点，然后直接跳到 `call   1390 <exit@plt>` 这一句处，完整的跳过了 `send_msg` 函数的执行，从而使得服务器无从知道我们的炸弹爆炸了。

    这对应我们的 `.gdbinit` 文件中的如下代码：

    ```bash
    # 为 explode_bomb 中触发 send_msg 函数的地方设置断点
    b *(explode_bomb + 0x44)
    # 为此断点编程
    command
    # 直接跳到 exit 退出函数处，跳过发送信息流程
    j *(explode_bomb + 0x81)
    end
    ```
```

得到：

![Cleanshot-2024-01-13-at-01 54 32@2x](https://github.com/Innei/Shiro/assets/36695271/7cfb1107-4fe8-4e98-aba9-6c65a4d34956)

错误地触发了引言块的语法。

预期：

![Cleanshot-2024-01-13-at-01 55 55@2x](https://github.com/Innei/Shiro/assets/36695271/8c8b21ec-6aa7-419f-8fee-7408d570a877)


### Reproduction

见说明

### System Info

```Shell
no need.
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by BLxcwg666** [comment]
我也遇到了，~~感觉mx用的markdown解析器是纯md解析~~，我从typecho的markdown搬过来就乱了

**Comment by Innei** [comment]
这种不是正规的 markdown 规范，暂不不做支持
