### ISSUE TITLE
今天更新了一下 Mix Space 发现了一个关于‘手记’页面的BUG

### ISSUE THREAD

**Issue by laogou717** [Innei/Shiro#243]
### Describe the bug

**升级空间之后 点击撰写手记**
<img width="292" alt="image" src="https://github.com/Innei/Shiro/assets/128354383/aadcb3d7-f3dc-42e6-a070-d70abe55bd8a">

**这里没办法制定ID**

<img width="1135" alt="image" src="https://github.com/Innei/Shiro/assets/128354383/45348223-617f-48ca-8974-cf909430a7c6">

**这意味着之前版本创建的文章不能删除,只要删除在主页点击书记就会找不到这篇文章,然后就会始终是错误页面,当然这个只限于像我这样刚部署的人**

<img width="934" alt="image" src="https://github.com/Innei/Shiro/assets/128354383/8d928b9e-248d-48e1-aaf1-4f2f016b4231">

### Reproduction

[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {   digest: '3257579095' }

### System Info

```Shell
无
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by laogou717** [comment]
因为我刚部署这个项目,在前两天随便创建了一篇文章,给文章Slug填写的是‘1’,而今天我尝试写专栏时就把这个唯一的文章删除掉了,就出现了这样的页面错误,然后我就回到了管理页面,发现创建文章没办法指定slug了,但其它页面时正常的

**Comment by Innei** [comment]
nid 不能改，不能自定义这是硬设定。

**Comment by laogou717** [comment]
> nid 不能改，不能自定义这是硬设定。
感谢大佬回复,是这样的我的后台现在只留下了一篇文章,但是前端依然会在加载出所以元素后,显示一个最初创建的名为 0 的手记,即使后端已经不存在了,但它一直在,我想请教下,是否能手动删去这个
<img width="2199" alt="image" src="https://github.com/Innei/Shiro/assets/128354383/1b2bf7c8-1b1e-4699-951a-9bb00a9dc2fc">
<img width="249" alt="image" src="https://github.com/Innei/Shiro/assets/128354383/1e09ce4d-2aa8-4c64-a363-3caede1e90e7">
