### ISSUE TITLE
在文章有多级标签的情况下右边的文章目录会乱跑

### ISSUE THREAD

**Issue by BLxcwg666** [Innei/Shiro#261]
### Describe the bug

比如说就是文章有类似这种多级标签
```
#H1
text
##H2
text
###H3
```
然后右边的文章目录点击的时候会跟丢 / 乱跳  
好像多了才会）
![image](https://github.com/Innei/Shiro/assets/66854530/ccafc0da-0a33-405a-ab1b-f3588acb6537)
test site：https://blog.xcnya.cn/posts/build/68.html
还是说我哪里改坏了（  
my fork：https://github.com/BLxcwg666/Shiro

### Reproduction

what

### System Info

```Shell
Build on Vercel
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
标题有重名。
