### ISSUE TITLE
Algolia搜索集成不生效？

### ISSUE THREAD

**Issue by lookwake** [Innei/Shiro#262]
参考[官方教程](https://mx-space.js.org/usage/search)配置的algolia搜索功能，但是ctrl k会focus浏览器的聚焦地址栏，并没有其他的特别的地方？

浏览器：Firefox，chromium也试过不可以。

Shiro版本：与 `innei/shiro` 同步
core版本：`v4.10.8`

**Comment by Innei** [comment]
什么浏览器啊

**Comment by Innei** [comment]
新版本已修复
