### ISSUE TITLE
✍️关于Openai api 生成摘要,是否需要额外配置东西。

### ISSUE THREAD

**Issue by laogou717** [Innei/Shiro#267]
### Describe the bug

![image](https://github.com/Innei/Shiro/assets/128354383/a6453d7d-2bae-47b9-a1bb-c047fe7893a1)
**我在尝试填写自己的api密钥到窗口中,然后生成,等了很久没有反应。**
然后我在浏览器控制台看到了这样的提示:
```
Uncaught (in promise) Error: It looks like you're running in a browser-like environment.

This is disabled by default, as it risks exposing your secret API credentials to attackers.
If you understand the risks and have appropriate mitigations in place,
you can set the `dangerouslyAllowBrowser` option to `true`, e.g.,

new OpenAI({ apiKey, dangerouslyAllowBrowser: true });

https://help.openai.com/en/articles/5112595-best-practices-for-api-key-safety

    at new _a (index-xAWrx8yA.js:5337:8476)
    at o (index-xAWrx8yA.js:5348:55)
    at et (index-xAWrx8yA.js:36:82497)
    at c (index-xAWrx8yA.js:1427:1662)
    at Hp (index-xAWrx8yA.js:14:59186)
    at bd (index-xAWrx8yA.js:14:59265)
    at HTMLButtonElement.t (index-xAWrx8yA.js:14:123463)
```
它说我试图在浏览器环境下直接使用Openai API,这是不被允许的,不知道是不是意味着项目的某些地方配置不到位。
我对方面不太明白,希望大佬有时间了可以指点一下。🙏

### Reproduction

无

### System Info

```Shell
无
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
感谢提醒，这个功能我已经很久没用了，不知道 openai 更新对这个做了限制。

另外这个 issue 不属于此项目的范畴，你应该在 mx-space/admin 中提问

**Comment by Innei** [comment]
另外我在 admin 中已经加了这个参数，升级之后已经就能解决
