### ISSUE TITLE
手记cover出现请求跨域的情况

### ISSUE THREAD

**Issue by SliverKeigo** [Innei/Shiro#279]
内容区和cover是同一张图片，内容区的图片能正常显示但Cover出现请求跨域的情况
![image](https://github.com/Innei/Shiro/assets/112426853/cbf414b6-559d-4ef7-a9a0-21417f59e18e)
![image](https://github.com/Innei/Shiro/assets/112426853/8d4d6ac1-0975-4066-87ed-db2b9253497b)
![image](https://github.com/Innei/Shiro/assets/112426853/c58bac44-2ff6-4ddf-939a-9954f28672ab)

**Comment by Innei** [comment]
跨域是你设置的问题，这里不做解答

**Comment by beanljun** [comment]
> 内容区和cover是同一张图片，内容区的图片能正常显示但Cover出现请求跨域的情况
> ![image](https://github.com/Innei/Shiro/assets/112426853/cbf414b6-559d-4ef7-a9a0-21417f59e18e)
> ![image](https://github.com/Innei/Shiro/assets/112426853/8d4d6ac1-0975-4066-87ed-db2b9253497b)
> ![image](https://github.com/Innei/Shiro/assets/112426853/c58bac44-2ff6-4ddf-939a-9954f28672ab)
> 

解决了吗，我也出现了跨域的问题
