### ISSUE TITLE
Markdown 语法：加载远程 React 组件

### ISSUE THREAD

**Issue by Innei** [Innei/Shiro#289]
新 Markdown 语法:

````markdown
```component
import=https://cdn.jsdelivr.net/npm/@innei/react-cdn-components@0.0.7/dist/components/Firework.js
name=MDX.Firework
height=25
```
````

用来加载一个远程 React 组件。

实例项目：

https://github.com/Innei/shiro-remote-components

参数参见：

https://github.com/Innei/shiro-remote-components/blob/main/README.md

上面的 Demo:

https://github.com/Innei/Shiro/assets/41265413/9d7e03ea-6486-40d8-b5ff-27a893a228de

https://shiro.innei.in/#/markdown 

React Remote Component Render 章节

**Comment by zhuozhiyongde** [comment]
我草 这也太酷了
