### ISSUE TITLE
全局前端调用api

### ISSUE THREAD

**Issue by NekoTC** [Innei/Shiro#292]
### 抛弃 Serverless Function

考虑一下后续抛弃 Serverless Function 直接在前端引用 API 吗
如果被打的话前端会带着后端一起死，有点烦人的，，，
![IMG_20240212_232652_969](https://github.com/Innei/Shiro/assets/96970949/a337d8e3-5f43-4815-9b22-b4c5384527a6)
![IMG_20240212_232656_124](https://github.com/Innei/Shiro/assets/96970949/8d2a1f20-46e3-4810-b64f-ec3141c88d0c)

### Suggested solution

抛弃 Serverless Function，API 全部在前端调用

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
哥 这是 Server Component 没办法的事

**Comment by Innei** [comment]
哎 我也被打 持续到现在了

**Comment by Dreamer-Paul** [comment]
> 哥 这是 Server Component 没办法的事

哈哈哈，怎么我感觉这和 RSC 没啥关系，只要网站是 SSR 就会请求
