### ISSUE TITLE
按照 VitePress 的格式小改了一下外部链接的样式，不知道要不要交个 PR？

### ISSUE THREAD

**Issue by zhuozhiyongde** [Innei/Shiro#298]
### Clear and concise description of the problem

如题，前后对比：

（左为修改后，右为修改前）

<img width="891" alt="image" src="https://github.com/Innei/Shiro/assets/36695271/baaa12fb-30d8-4052-9cc2-818b4ef92e2f">

主要是换了图标 + 让前面的 logo 变小了一点，并且通过 inline-flex 使这三个元素垂直居中对齐了。

### Suggested solution

修改代码可见于：https://github.com/zhuozhiyongde/Shiro/commit/d5d938615f16042aa1be8886e36020e7d9567fe4

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
好耶
