### ISSUE TITLE
emmm 我有个呆呆的问题

### ISSUE THREAD

**Issue by king-zhangbn** [Innei/Shiro#301]
### Describe the bug

emmm 我有个呆呆的问题，就是这个主页头像如何设置？？？站点的我会，但是首页简介边上和顶部的我是真滴找不到，我尝试过在云函数里面寻找，但是只能找到站点头像配置

### Reproduction

no

### System Info

```Shell
no
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
![image](https://github.com/Innei/Shiro/assets/41265413/0d787fe2-5186-4ba9-83a5-952ed27a31e8)
这里

**Comment by bwdrea** [comment]
确实是个呆呆的问题呢
