### ISSUE TITLE
[Feature Request] Shiki line number

### ISSUE THREAD

**Issue by zhuozhiyongde** [Innei/Shiro#309]
### Clear and concise description of the problem

现在的 shiki 不支持 line number。

### Suggested solution

https://github.com/shikijs/shiki/issues/3

### Alternative

似乎需要通过修改 css 支持，但我试了一下没成功（

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
原本是有的，后来我删了。感觉没有必要

**Comment by zhuozhiyongde** [comment]
但是原本的 highlighter 是有的，而且有时候基于行数的表述也需要它，或许佬可以给个代码吗，我也可以就在自己的那个 fork 加一下（

**Comment by Innei** [comment]
DONE
