### ISSUE TITLE
支持单页面/文章自定义注入js

### ISSUE THREAD

**Issue by yhrwd** [Innei/Shiro#312]
### Clear and concise description of the problem

我试过在文章中添加<head>标签，以及用md注入js的语法，但那并不起作用，因此我想要可以为不同的页面添加不同的js，以此来实现一些特殊或有趣的功能

### Suggested solution

sorry，I'm not very familiar with typescript

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by BLxcwg666** [comment]
好像是支持直接贴script标签的（在 api/proxy/qaqdmin 后台中

**Comment by yhrwd** [comment]
> 好像是支持直接贴脚本标签的（在 API/proxy/qaqdmin 后台中

可以详细说说嘛，我这边貌似不行

**Comment by Innei** [comment]
直接在 md 中插入 script 就行了
