### ISSUE TITLE
[Question] How to add social links?

### ISSUE THREAD

**Issue by seriaati** [Innei/Shiro#313]
![image](https://github.com/Innei/Shiro/assets/61446626/603f1887-40cc-4b8b-94f7-a2af3c18dd33)

**Comment by Innei** [comment]
Shiro can support and parse those types for now.

```ts
{
  github: 'GitHub',
  twitter: 'Twitter',
  telegram: 'Telegram',
  mail: 'Email',
  rss: 'RSS',
  email: 'Email',
  feed: 'RSS',
  bilibili: '哔哩哔哩',
  netease: '网易云音乐',

  qq: 'QQ',
  wechat: '微信',
  weibo: '微博',

  x: 'X',
}
```

**Comment by pcccccc** [comment]
> ```ts
> github
> ```

![3410729101](https://github.com/Innei/Shiro/assets/13974510/fe695780-0e18-45e1-89f9-027b3cf6284d)

可以请问下我的社交链接下为什么只有四项吗？

面板版本: 4.2.1

系统版本：5.4.3

页面来源：server

**Comment by pcccccc** [comment]
> 感谢你的邀请。请在“设置（设定）->社交平台ID（社交平台ID录入）”下找到配置项进行输入。
> 
> 其配置选项的详细信息可以参考图中。
> 
> ![图像](https://private-user-images.githubusercontent.com/69001561/314044605-3ccf8c5c-d2cb-44f2-aff1-fd27d341811d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NjI1OTksIm5iZiI6MTcxMTc2MjI5OSwicGF0aCI6Ii82OTAwMTU2MS8zMTQwNDQ2MDUtM2NjZjhjNWMtZDJjYi00NGYyLWFmZjEtZmQyN2QzNDE4MTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDAxMzEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNWMyZTZmY2FlNjRjMmJkMGU4YTY2OTgwYzZkZGJjZTJjYWQ5YmIyMDA0YTdlMjRkOTc4MmY5YjEyMTc1MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wXxty00YyUU95G4m6eV0Xz5DB3ArkVUjd_daObsws18)
> 
> 翻译自 ChatGPT

![3410729101](https://github.com/Innei/Shiro/assets/13974510/1a984d5f-1208-4b85-a344-4a280c5ca5d9)

可以请问一下，为什么我的社交平台ID 录入只有四项呢。这个要在哪里修改配置呢。

面板版本: 4.2.1

系统版本：5.4.3

页面来源：server

**Comment by seriaati** [comment]
那個欄位裡可以直接輸入，不一定要按著提供的選項選擇。

**Comment by pcccccc** [comment]
> 那個欄位裡可以直接輸入，不一定要按著提供的選項選擇。

好的， 感谢🙏
