### ISSUE TITLE
docker-compose 编译到static,feed报错。

### ISSUE THREAD

**Issue by pcccccc** [Innei/Shiro#321]
### Describe the bug

错误日志：

90.9 info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
190.9    Collecting page data ...
192.5  ⚠ Using edge runtime on a page currently disables static generation for that page
213.3    Generating static pages (0/31) ...
   Generating static pages (7/31) 
   Generating static pages (15/31) 
   Generating static pages (23/31) 
217.4 
217.4 Error occurred prerendering page "/feed". Read more: https://nextjs.org/docs/messages/prerender-error
217.4 
217.4 SyntaxError: Unexpected token < in JSON at position 0
217.4     at JSON.parse (<anonymous>)
217.4     at parseJSONFromBytes (node:internal/deps/undici/undici:4747:19)
217.4     at successSteps (node:internal/deps/undici/undici:4718:27)
217.4     at fullyReadBody (node:internal/deps/undici/undici:1433:9)
217.4     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
217.4     at async specConsumeBody (node:internal/deps/undici/undici:4727:7)
217.4     at async Promise.all (index 0)
217.4     at async es (/app/.next/server/app/feed/route.js:1:19838)
217.4     at async /app/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484
217.4     at async eI.execute (/app/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:32486)
 ✓ Generating static pages (31/31) 
217.5 
217.5 > Export encountered errors on following paths:
217.5   /feed/route: /feed
217.6  ELIFECYCLE  Command failed with exit code 1.

Dockerfile:35

  33 |     ENV CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
  34 |     
  35 | >>> RUN pnpm build
  36 |     
  37 |     FROM base AS runner

### Reproduction

修改docker-compose.yml后执行docker-compose up -d

### System Info

```Shell
OS:Ubuntu 22.04.4 LTS
Docker version 26.0.0, build 2ae903e
docker-compose version 1.29.2, build unknown
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lnbiuc** [comment]
Same error when deploying vercel

![image](https://github.com/Innei/Shiro/assets/85148161/bd82c789-a5f4-4ed2-b9b9-6a8a66131637)
