### ISSUE TITLE
最新版，首页“最近发生的事” URL 缺失分类。

### ISSUE THREAD

**Issue by HyakutakeGh** [Innei/Shiro#346]
### Describe the bug

最新版，首页“最近发生的事” URL 缺失分类。
例如 文章为 /posts/CCC/XXX
而在首页最近发生的事情，URL为：/posts/XXX
导致404

### Reproduction

deploy

### System Info

```Shell
web
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
更新 core

**Comment by HyakutakeGh** [comment]
> 更新 core

我是同时更新 core + shiro 的。

**Comment by Innei** [comment]
地址发下

**Comment by HyakutakeGh** [comment]
hi.hyakutake.site
