### ISSUE TITLE
是否有计划加强分享的功能

### ISSUE THREAD

**Issue by HyakutakeGh** [Innei/Shiro#352]
### Clear and concise description of the problem

对于文章或者手记，希望推出更好的分享功能。加强对站点的宣传。

### Suggested solution

1. 是否可以尝试以海报的形式分享内容。
2. 或者用卡片链接的方式发送到社交媒体中。

PS: 顺道问一下，闭源版本如何才能加入使用？文档中未体现。

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
直接复制链接就好，文章链接支持 OpenGraph，一般海外社交媒体都支持解析这个

**Comment by Ssttar** [comment]
> PS: 顺道问一下，闭源版本如何才能加入使用？文档中未体现。
sponsor 10$ innei sponsor界面有写
