### ISSUE TITLE
博客中添加配置相关模块

### ISSUE THREAD

**Issue by binaryYuki** [Innei/Shiro#357]
### Clear and concise description of the problem

Hi～

感谢大佬开源这么好看的博客 让大家都能用上

想问下这样的配置框使用 component 做的吗 是否可以在使用该主题的博客网站中实现呢～

<img width="847" alt="截屏2024-05-09 22 59 56" src="https://github.com/Innei/Shiro/assets/60097976/88467f9c-a643-42de-a363-bd4838bb94c2">

### Suggested solution

前端小白 暂时想不到

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
文档使用是 MDX，可以在 markdown 中内嵌 React 组件，其代价是需要静态编译，而无法在动态的内容中使用。

作为代替，Shiro flavored markdown syntax 中可以加载远程 React 组件，参考 https://innei.in/posts/dev-story/nextjs-react-load-and-render-remote-component
