### ISSUE TITLE
ERR_PNPM_BAD_PM_VERSION err when deploying

### ISSUE THREAD

**Issue by matto49** [Innei/Shiro#366]
### Describe the bug

使用vercel部署shiro的时候，出现pnpm的version落后问题
![81a95104f6de78e3a33acdd28137e85a](https://github.com/Innei/Shiro/assets/54560462/27a1e1ce-6144-49c1-8f32-2ac68d162f9c)

### Reproduction

参照文档使用vercel启动项目

### System Info

```Shell
macOs 14.4.1
node 20.12.1
edge
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by matto49** [comment]
参照https://vercel.com/docs/deployments/configure-a-build#corepack
解决方案可以是将ENABLE_EXPERIMENTAL_COREPACK放到项目的env里面
貌似在这个操作不会读取项目里的env，试着改了一下.env.template但是没有生效
可以在docs文档里的环境配置那一步，增加这个option吗

**Comment by wixxm** [comment]
项目里边已经给你了提示，看报错的下一行吧
COREPACK_ENABLE_STRICT添加到环境变量里边参数设为0.
然后重新部署就行了。仔细看提示。

**Comment by Innei** [comment]
> vercel.com/docs/deployments/configure-a-build#corepack

@matto49 在 vercel 的 env 加这个

**Comment by wixxm** [comment]
> > vercel.com/docs/deployments/configure-a-build#corepack
> 
> @matto49 在 vercel 的 env 加这个

直接在变量加入COREPACK_ENABLE_STRICT=0也可以把？ 我是看提示加的会不会影响程序？

**Comment by matto49** [comment]
> > > vercel.com/docs/deployments/configure-a-build#corepack
> > 
> > 
> > @matto49 在 vercel 的 env 加这个
> 
> 直接在变量加入COREPACK_ENABLE_STRICT=0也可以把？ 我是看提示加的会不会影响程序？

这个是忽略pnpm版本问题哈
![1a9ae0e1f07699f55b6c6a34d38efbc3](https://github.com/Innei/Shiro/assets/54560462/0b10140f-b7a1-49ce-bd51-ed02b96deee8)
pnpm版本没有匹配的时候，会遇到这个问题
见https://github.com/pnpm/pnpm/issues/6424#issuecomment-1515748464
安装好对的pnpm版本之后就成功安上包了
