### ISSUE TITLE
依赖 daisyui 版本大于等于v4.12.8会导致代码块滚动条样式和原有样式冲突

### ISSUE THREAD

**Issue by Airi-Iris** [Innei/Shiro#390]
### Describe the bug

如题。

拉取最新代码并构建后发现代码块在hover与正常情况下的滚动条样式冲突

正常情况下：
![image](https://github.com/Innei/Shiro/assets/60839179/9a2cc92a-16f6-4f97-9cfe-5340e0be67b4)

hover时：
![image](https://github.com/Innei/Shiro/assets/60839179/e5acf0da-2aa0-4cd5-bfbf-ffc6e78a44c7)

通过查阅 daisyui v4.12.8的改动得知，daisyui 添加了在所有元素hover时滚动条的样式，如下图
![image](https://github.com/Innei/Shiro/assets/60839179/44550502-546c-4515-8408-2cb353602de0)

### 可能的解决方法
修改 src/styles/tailwindcss.css 中的第47行,如下图所示
![image](https://github.com/Innei/Shiro/assets/60839179/217b0d77-8c81-4a9c-ad77-3aa5eaa39826)
结果:
![image](https://github.com/Innei/Shiro/assets/60839179/1f371a40-5db6-421b-a6e7-2d09431b28ed)

### Reproduction

见描述

### System Info

```Shell
no need.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
Thanks
