### ISSUE TITLE
移动端-文章内图片

### ISSUE THREAD

**Issue by gsh3ll** [Innei/Shiro#394]
### Clear and concise description of the problem

移动端点击图片会打开一个新的标签页

### Suggested solution

希望可以和 pc 端一样，在当前页面显示。

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
不考虑，因为那个效果不好
