### ISSUE TITLE
思考页面中评论表情问题

### ISSUE THREAD

**Issue by h1k4r** [Innei/Shiro#398]
### Describe the bug

如图
![image](https://github.com/Innei/Shiro/assets/60561049/740db2b8-d178-4839-81ee-ca2ca148d53d)
![image](https://github.com/Innei/Shiro/assets/60561049/42dfd219-c1ce-4fd8-9394-201d3b851035)

### Reproduction

none

### System Info

```Shell
none
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
3Q, fixed
