### ISSUE TITLE
项目自适应问题

### ISSUE THREAD

**Issue by SnowballXueQiu** [Innei/Shiro#399]
### Describe the bug

在我填写项目的时候，发现由于使用flex布局，导致该colum的max-height变化，从而影响了Icon的大小，如图所示：

![QQ_1720889348700](https://github.com/user-attachments/assets/494dc1a4-1ce2-45f6-b9e7-62b025ac0fbd)

### Reproduction

添加不一样长度的项目标题即可

### System Info

```Shell
Windows 11
Google Chrome latest version
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
Fixed
