### ISSUE TITLE
禁止访问或者 API 服务出现问题

### ISSUE THREAD

**Issue by magblank** [Innei/Shiro#404]
后端使用docker搭建在购买的阿里云服务器中，使用宝塔配置的方向代理，
前端按照文档中使用vercel搭建，问题如图
![font_log](https://github.com/user-attachments/assets/1b24bbf7-c1a6-4f92-9195-e09bbb37fbc7)
#### docker-compose.yml
![image](https://github.com/user-attachments/assets/a9983bd0-5d08-4dea-9ee0-3a3885949b51)
#### 反向代理：
```server
{
    listen 80;
    listen 443 ssl http2 ;
    server_name api.blmfex.cn;
    index index.php index.html index.htm default.php default.htm default.html;
    root /www/wwwroot/api.blmfex.cn;
    #CERT-APPLY-CHECK--START
    # 用于SSL证书申请时的文件验证相关配置 -- 请勿删除
    include /www/server/panel/vhost/nginx/well-known/api.blmfex.cn.conf;
    #CERT-APPLY-CHECK--END

    #SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
    #error_page 404/404.html;
    #HTTP_TO_HTTPS_START
    if ($server_port !~ 443){
        rewrite ^(/.*)$ https://$host$1 permanent;
    }
    #HTTP_TO_HTTPS_END
    ssl_certificate    /www/server/panel/vhost/cert/api.blmfex.cn/fullchain.pem;
    ssl_certificate_key    /www/server/panel/vhost/cert/api.blmfex.cn/privkey.pem;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    add_header Strict-Transport-Security "max-age=31536000";
    error_page 497  https://$host$request_uri;

    #SSL-END

    #ERROR-PAGE-START  错误页配置，可以注释、删除或修改
    error_page 404 /404.html;
    #error_page 502 /502.html;
    #ERROR-PAGE-END
    #PHP-INFO-START  PHP引用配置，可以注释或修改
    #清理缓存规则
    location ~ /purge(/.*) {
        proxy_cache_purge cache_one $host$1$is_args$args;
        #access_log  /www/wwwlogs/api.blmfex.cn_purge_cache.log;
    }
	#引用反向代理规则，注释后配置的反向代理将无效
	include /www/server/panel/vhost/nginx/proxy/api.blmfex.cn/*.conf;

	include enable-php-00.conf;
    #PHP-INFO-END

    #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
    include /www/server/panel/vhost/rewrite/api.blmfex.cn.conf;
    #REWRITE-END
    #禁止访问的文件或目录
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.env|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }
    #一键申请SSL证书验证目录相关设置
    location ~ \.well-known{
        allow all;
    }
    #禁止在证书验证目录放入敏感文件
    if ( $uri ~ "^/\.well-known/.*\.(php|jsp|py|js|css|lua|ts|go|zip|tar\.gz|rar|7z|sql|bak)$" ) {
        return 403;
    }
    access_log  /www/wwwlogs/api.blmfex.cn.log;
    error_log  /www/wwwlogs/api.blmfex.cn.error.log;
}
```

##### include /www/server/panel/vhost/nginx/proxy/api.blmfex.cn/*.conf;
```
# 反向代理开始
# WebSocket
location /socket.io {
  proxy_pass http://127.0.0.1:2333/socket.io; 
  proxy_set_header Host $host; 
  proxy_set_header X-Real-IP $remote_addr; 
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
  proxy_set_header REMOTE-HOST $remote_addr; 
  proxy_set_header Upgrade $http_upgrade; 
  proxy_set_header Connection "upgrade"; 
  proxy_buffering off;
  proxy_http_version 1.1; 
  add_header Cache-Control no-cache; 
}
# Others
location / {
  proxy_pass http://127.0.0.1:2333; 
  proxy_set_header Host $host; 
  proxy_set_header X-Real-IP $remote_addr; 
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
  proxy_set_header REMOTE-HOST $remote_addr; 
  add_header X-Cache $upstream_cache_status; 
}
# 反向代理结束
```
#### 前端详情：
![vercel_v_log](https://github.com/user-attachments/assets/b668417a-3b8c-4c06-b890-5f3e92070b63)
![domains_](https://github.com/user-attachments/assets/776b3dfe-addf-417c-a6e0-ce33c4aa4bab)

#### 后端日志
![mx-server-log](https://github.com/user-attachments/assets/54237af5-c49f-4bce-9b5b-b2318974b961)
![image](https://github.com/user-attachments/assets/457ddbdd-72fc-45a2-9832-240351c88def)
#### 前端vercel日志：
![vercel_log](https://github.com/user-attachments/assets/6cee3afb-1bc4-4518-8bbd-ab51a774b8b0)
#### nginx部分访问日志：
![image](https://github.com/user-attachments/assets/6c36c1cf-c70e-4d95-bcd1-772501764d88)

大佬救救 QAQ

**Comment by Innei** [comment]
你 shiro 配置没填哇

**Comment by Innei** [comment]
https://mx-space.js.org/themes/shiro#%E8%AE%BE%E7%BD%AE%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE

**Comment by magblank** [comment]
还真是（尴尬
![9F51B20F](https://github.com/user-attachments/assets/c1d3f66a-479a-4076-9649-e4092e27bc95)

**Comment by xkfe** [comment]
@magblank 请问下你是配置了什么解决了 “禁止访问或者 API 服务出现问题”？

**Comment by magblank** [comment]
我的账号已经登陆不上了，我用邮箱回复，不确定你能不能收到。
我也只是猜测，会不会是你打错了，仔细看一下
云函数的编辑下面的名称和引用是否正确，其他服务是否正常启动等等
                    Original Email         
         
       
From：                  "小凯同学"         ***@***.***&gt;                 
Sending time：         2024-11-14- 18:11 
To：                  "Innei/Shiro"         ***@***.***&gt;                 
Cc recipient：                  "Mag"         ***@***.***&gt;         ,                "Mention"         ***@***.***&gt;                 
Subject：         Re: [Innei/Shiro] 禁止访问或者 API 服务出现问题 (Issue #404) 




@magblank&nbsp;请问下你是配置了什么解决了 “禁止访问或者 API 服务出现问题”？
