### ISSUE TITLE
请教作者大佬

### ISSUE THREAD

**Issue by DawnMagnet** [Innei/Shiro#408]
我有两个小小的问题

- 主页可以打开,但是/dashboard打不开(禁止访问或者 API 服务出现问题),这个需要检查哪个nginx配置呢
- 有的时候头像不显示
- 改完云函数里面的配置,需要相当一段时间才能加载到主页上

**Comment by DawnMagnet** [comment]
好像这三个问题都是第三个问题(无语了
上传完头像卡了一会,第一个和第二个问题都解决了哈哈哈

**Comment by Shalomguan** [comment]
头像我过了好久还没加载上去
