### ISSUE TITLE
docker安装mx-space报错

### ISSUE THREAD

**Issue by yizhimao213** [Innei/Shiro#426]
### Describe the bug

![image](https://github.com/user-attachments/assets/8bfc782b-3d0f-4544-bf1e-bf10147d79d6)
显示这个，不支持吗？

### Reproduction

docker

### System Info

```Shell
Need to install the following packages:
envinfo@7.13.0
Ok to proceed? (y) y


  System:
    OS: Linux 5.4 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (4) arm64 Neoverse-N1
    Memory: 7.06 GB / 23.43 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.10.0 - /www/server/nodejs/v20.10.0/bin/node
    Yarn: 1.22.22 - /www/server/nodejs/v20.10.0/bin/yarn
    npm: 10.8.2 - /www/server/nodejs/v20.10.0/bin/npm
    pnpm: 9.7.0 - /www/server/nodejs/v20.10.0/bin/pnpm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
目前没有提供 arm64 版本的 dockerfile

**Comment by Innei** [comment]
此问题应该属于 mx-space，因此关闭
