### ISSUE TITLE
目录条

### ISSUE THREAD

**Issue by yizhimao213** [Innei/Shiro#429]
### Describe the bug

手机端目录条过长的情况下滑不动
![4C65654E-90A7-4278-B6DB-A85D40EF67AD](https://github.com/user-attachments/assets/6f3772ae-c6db-4558-af49-f1b132e1d348)

https://www.ixoxi.cn/posts/biji/yy1

### Reproduction

目录

### System Info

```Shell

https://www.ixoxi.cn/posts/biji/yy1

```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
目前应该已经修复？

**Comment by yizhimao213** [comment]
修复了
