### ISSUE TITLE
Excalidraw

### ISSUE THREAD

**Issue by yizhimao213** [Innei/Shiro#435]
### Describe the bug

Excalidraw插入图片,显示图片失败
![1724082569405](https://github.com/user-attachments/assets/8e58feaf-9188-47db-8dad-07c9f92240d5)

![1724082506172](https://github.com/user-attachments/assets/17d2f52a-a0be-4ec1-8b2b-d3ade90274e4)

### Reproduction

Excalidraw

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
不支持图片，也不会支持内嵌图片
