### ISSUE TITLE
/timeline 下 command + 单击不会打开新标签页

### ISSUE THREAD

**Issue by chesha1** [Innei/Shiro#436]
### Describe the bug

/timeline 下 command + 单击某个文章，不会打开新标签页

在其他页面中，比如 /posts 下，command + 单击能正常打开新标签页

### Reproduction

环境：chrome 127.0.6533.120, macos sonoma 14.5

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
Timeline 默认是 Peek 预览 不走链接的逻辑。
