### ISSUE TITLE
TMDB卡片

### ISSUE THREAD

**Issue by yizhimao213** [Innei/Shiro#441]
### Describe the bug

TMDB卡片显示不了内容，只有一个框，里面没内容。
https://www.ixoxi.cn/thinking

### Reproduction

![image](https://github.com/user-attachments/assets/a8e26701-7209-47cc-906c-f3eae800dcd7)
### **也已经配置了api**
![image](https://github.com/user-attachments/assets/b737468b-28e5-4f58-bb93-3c21222c88e6)

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by liyown** [comment]
这个我知道  作者使用的是 `Authorization` 的鉴权方法 ，但是我看API 现在是使用 `query` 方法，我试了直接用 `Authorization`  是无法请求的；
![image](https://github.com/user-attachments/assets/0ef1ba3f-e877-4256-ab7a-09ac51506304)
改为`query` 参数：
![image](https://github.com/user-attachments/assets/ee160b53-6589-4ca4-bd27-b21b4776594c)
最新的修改我追加到了PR里面，或者你可以参考#437
