### ISSUE TITLE
禁止访问或者 API 服务出现问题

### ISSUE THREAD

**Issue by stmoonar** [Innei/Shiro#457]
### Describe the bug

Vercel可以正常访问但是自己构建就禁止访问或者 API 服务出现问题，docker-compose和node运行release包都试了甚至重装了一遍还是一样的错误，后端是正常的。

### Reproduction

这是vercel的正常页面：https://shiro-eight-hazel.vercel.app/
然后我自己的：https://stmoonar.me/
![image](https://github.com/user-attachments/assets/46103901-c83c-4319-a4d2-38a8bce3f735)
控制台报错是关于clerk的
![image](https://github.com/user-attachments/assets/dcf02668-cbc3-48e8-aa46-a835e1076674)
这是我的前端配置文件：
![image](https://github.com/user-attachments/assets/6cd7cba5-4def-4c11-a726-83a4906ce53d)
大佬可以帮我看看是什么原因吗，谢谢了。

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
哥，不好意思，忘发版了。

现在试试呢。1.2.0 的

**Comment by stmoonar** [comment]
> 哥，不好意思，忘发版了。
> 
> 现在试试呢。1.2.0 的

感谢大佬，现在好了
