### ISSUE TITLE
前端使用gh登录时无法回调

### ISSUE THREAD

**Issue by Alcexn** [Innei/Shiro#458]
### Describe the bug

前端使用gh登录时无法回调，具体表现为通过blog.alcex.cn登录时，会跳转到https://blog-api.alcex.cn/api/v2/auth/signin?error=MissingCSRF 然后提示Unable to sign in.，如果继续登录则会跳转到后台并提示是否设定为主人账号，但是前端仍没有任何登录信息，通过gh也无法登录后台只能使用密码，怀疑是前面MissingCSRF导致，但是排查过cdn，配置找不出来什么问题，控制台报错如下图，oauth也是按照文档配置，恳求大佬有空的时候看一下，谢谢

### Reproduction

![image](https://github.com/user-attachments/assets/7b8caa39-cf78-47bd-af90-1018f11680d1)
![image](https://github.com/user-attachments/assets/46da1313-ac45-41d8-84da-77a84e93a5a5)

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Alcexn** [comment]
使用的vercel部署，似乎只有vercel会产生这样的问题

**Comment by YuziO2** [comment]
同样的问题，请问楼主解决了没？

**Comment by Alcexn** [comment]
> 同样的问题，请问楼主解决了没？

使用单域名部署就没问题了
