### ISSUE TITLE
管理中台无法更新到4.7.3

### ISSUE THREAD

**Issue by bwdrea** [Innei/Shiro#466]
### Describe the bug

目前管理中台版本号：4.6.2
目前系统版本：6.1.3
在管理中台界面点击右上角更新管理中台到4.7.3版本时报错，提示不能跨版本更新，如下：
> The latest version is 4.7.3, current version is 4.6.2, can not cross-version upgrade.

是不是只能重新部署服务器了？

### Reproduction

![image](https://github.com/user-attachments/assets/39e369d6-7ab4-4888-89e9-b74ad4549a70)
![image](https://github.com/user-attachments/assets/944d4fb8-a7db-4f2f-8bed-49d4471f34ea)

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by DearVinking** [comment]
> [更新 Mix Space](https://mx-space.js.org/usage/update)

进入 core 所在文件夹，然后 `docker compose pull && docker compose up -d`

**Comment by bwdrea** [comment]
太感谢了，我一时晕了头，误以为自己Mix Space不是docker安装的
