### ISSUE TITLE
获取不到访客评论的网址

### ISSUE THREAD

**Issue by yuano0** [Innei/Shiro#47]
**mix-space版本：**
面板版本: 3.30.10
系统版本：4.2.12
页面来源：server
398 commits的版本
linux版本：Ubuntu 20.04

### 详细信息：
![https://img.yuano.cc/upload/xiaoyuanyuan1111.png](https://img.yuano.cc/upload/xiaoyuanyuan1111.png)
访客评论，填写自己的网站地址，提交评论后无法获取到网址。后台有留言显示，按照以前版本，点击名称即可跳转到访客的网站。

![https://img.yuano.cc/upload/test2.png](https://img.yuano.cc/upload/test2.png)
现在无法跳转。但是以前kami的留言，还是可以跳转的。

我尝试了一下，部署两个站点，使用同一个后台。

kami评论的留言，后台可以获取到评论网址，切到shiro也可以点击访问。
shiro评论的留言，后台无法正常获取到网址，在kami也无法打开。

**Comment by Innei** [comment]
Fixed
