### ISSUE TITLE
希望参考 shiro 的部分 UI 设计

### ISSUE THREAD

**Issue by Anxcyee** [Innei/Shiro#477]
hi，首先很抱歉我不能提出一个符合模板的 issue，我的问题可能不符合这两种模板。

目前我也在写一个个人网页，看到 shiro 非常简洁，美观，我非常喜欢您的设计。我能否参考 shiro 的部分设计？尤其是首页部分和顶部导航栏的设计。

当然我会注明设计的参考来源，明确表示参考了 shiro。

另外，我的 GitHub 账号目前无法提出 issue，临时使用此账号写下这个 issus。

**Comment by Innei** [comment]
可以的！欢迎
