### ISSUE TITLE
是我的配置出了什么问题吗出现了这样的报错

### ISSUE THREAD

**Issue by Shalomguan** [Innei/Shiro#482]
### Describe the bug

![IMG_1670](https://github.com/user-attachments/assets/cd073f7d-78b0-46bc-b002-da9a8a78c05f)
![IMG_1671](https://github.com/user-attachments/assets/ae5831d9-1e04-4c23-9f5f-a17047452b3d)

### Reproduction

就想这样

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ORyong** [comment]
请问您是怎么解决的呢，我也遇到了这种问题
