### ISSUE TITLE
网页在稍旧Chromium内核版本的浏览器的兼容性问题

### ISSUE THREAD

**Issue by SummerBeachhh** [Innei/Shiro#491]
作者您好，我在使用“百分浏览器(Chromium 102内核)”，浏览您的博客页面会出现排版错误，元素不能正常显示的问题（已开启安全模式禁用了所有扩展），因为我只是初学者，对前端知之甚少，所以想请教一下这是发生了什么？是因为旧版浏览器内核已经不能支持某个框架的特性了吗？我想在我部署的博客中修复这个问题，希望得到一些建议🙏
![image](https://github.com/user-attachments/assets/6289031d-8dc9-48da-9a43-ef5c38c70a11)

![image](https://github.com/user-attachments/assets/eb283a3e-f86a-4e3b-8af7-8169a033d2fc)

**Comment by Innei** [comment]
请升级浏览器内核。旧版浏览器不支持某些 CSS 特征
