### ISSUE TITLE
【求助】部署好服务端后报错日志

### ISSUE THREAD

**Issue by ZAIDU-Miren** [Innei/Shiro#495]
### Feature description

![PixPin_2024-11-24_09-58-43](https://github.com/user-attachments/assets/5493a518-472d-417d-869f-b638d58e5425)

部署后，访问哪个地址可以到主页嘞

### Validations

- [X] You know your feature request won't be accepted.

**Comment by ZAIDU-Miren** [comment]
![image](https://github.com/user-attachments/assets/c0cc1677-16be-4dda-ab6d-90cc8728bbc2)

**Comment by Innei** [comment]
你没有在创建一个配置，需要在云函数中创建一个配置

**Comment by ZAIDU-Miren** [comment]
> 你没有在创建一个配置，需要在云函数中创建一个配置

大佬，我的服务端是docker，你的前端也是，还需要吗？

**Comment by Innei** [comment]
和这个没关系，配置是都需要的

**Comment by Innei** [comment]
![CleanShot 2024-11-24 at 5  16 49@2x](https://github.com/user-attachments/assets/ab587023-5334-44bc-bded-5b4e18192485)

**Comment by ZAIDU-Miren** [comment]
> ![CleanShot 2024-11-24 at 5  16 49@2x](https://private-user-images.githubusercontent.com/41265413/389260691-ab587023-5334-44bc-bded-5b4e18192485.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NTUwODQsIm5iZiI6MTczMjQ1NDc4NCwicGF0aCI6Ii80MTI2NTQxMy8zODkyNjA2OTEtYWI1ODcwMjMtNTMzNC00NGJjLWJkZWQtNWI0ZTE4MTkyNDg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDEzMjYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0YWZiNGIwMjVlODA0YzhkNjFkNDdkYTIxNmQ3OGQ4ZjFkNmUwM2JjM2Y0YTMyN2QyNDhhODkwOWVjMzBhYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dsYQwMGNDgFOQFSaJuiXdV55DrbfyYg6SruJYL4RV20)

OK，我试试，感谢大佬，同时反馈一个跳转问题，用你默认的就行的对吧
![image](https://github.com/user-attachments/assets/5230a4a7-776f-41d3-ac6b-82db571a6358)

**Comment by ZAIDU-Miren** [comment]
还是不行，救命~
![image](https://github.com/user-attachments/assets/9401a440-fb5b-4136-8a3f-ff68d4aac797)
![image](https://github.com/user-attachments/assets/9cb4ec72-9893-4330-a3b3-030651307f77)

**Comment by ZAIDU-Miren** [comment]
![image](https://github.com/user-attachments/assets/c38f13cb-2b8b-4059-ad57-af6780153a0f)

**Comment by ZAIDU-Miren** [comment]
> ![image](https://private-user-images.githubusercontent.com/92215296/389283868-c38f13cb-2b8b-4059-ad57-af6780153a0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NjE1ODEsIm5iZiI6MTczMjQ2MTI4MSwicGF0aCI6Ii85MjIxNTI5Ni8zODkyODM4NjgtYzM4ZjEzY2ItMmI4Yi00MDU5LWFkNTctYWY2NzgwMTUzYTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDE1MTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYjQ3YjhjYTViY2VhMDgyNDVkMTY5ZTc1YTFhZTFiOWFiMDJhM2JiMDE2YzM2OGEzYzQ4MGM1MDRiOTJhYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6VEd5v0UlbBmhuqQjn-3qwY24uETw87sFSn5bTRcmkI)

![image](https://github.com/user-attachments/assets/d1f8e4b9-b4e0-4b8c-98aa-f2f15664a6dd)

**Comment by ZAIDU-Miren** [comment]
已解决，配置云函数还需要检查服务端的配置，同时下载
![image](https://github.com/user-attachments/assets/9220f486-5f85-4916-a9e0-0bac6ce3dfb1)

**Comment by juneDink** [comment]
请问，前后端都是试用docker部署的，有配置代理吗？（nginx），是否参考安装教程中的代理进行配置的？

**Comment by chenyuan-new** [comment]
> 已解决，配置云函数还需要检查服务端的配置，同时下载 ![image](https://private-user-images.githubusercontent.com/92215296/389331270-9220f486-5f85-4916-a9e0-0bac6ce3dfb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzODQzNDksIm5iZiI6MTczNTM4NDA0OSwicGF0aCI6Ii85MjIxNTI5Ni8zODkzMzEyNzAtOTIyMGY0ODYtNWY4NS00OTE2LWE5ZTAtMGJhYzZjZTNkZmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDExMDcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmOWMxM2UwZGQ2MWMxNTNiMTdiZWFmYWFlZDVkZjAyODgyZTI0N2JhOTE4NmI5MmVmZThmZmJiYzA0MDFjZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.w1B8AFWCUAoqXE7q09DfUhHsWRtlc2lZZDHbq1jIwWg)

测试下来应该是不需要配置这个的，应该是next的默认缓存的问题，清理缓存后就可以了。
