### ISSUE TITLE
禁止访问或者 API 服务出现问题

### ISSUE THREAD

**Issue by 2823602869** [Innei/Shiro#509]
### Feature description

![image](https://github.com/user-attachments/assets/d9744c40-1d26-4504-a4eb-fd8f15ecc2bd)
![image](https://github.com/user-attachments/assets/ec20fe66-dfd3-46d4-8899-471e6afa9c5c)
![image](https://github.com/user-attachments/assets/ca1e4ac6-2d7c-40d8-a9b5-29cc7523b145)
![image](https://github.com/user-attachments/assets/8c567b97-8ae0-4c75-9b6a-ea03d4cd67bc)
重新部署也是这样，麻烦大佬看看

### Validations

- [X] You know your feature request won't be accepted.

**Comment by 2823602869** [comment]
![image](https://github.com/user-attachments/assets/85aebd46-aeec-4e26-8149-db20c237909b)
![image](https://github.com/user-attachments/assets/2d66e502-f371-4e87-b6b2-1105b084ca48)
是不能修改这里面的默认配置吗，我发现删除一部分就会报[禁止访问或者 API 服务出现问题]

**Comment by Innei** [comment]
不要删，可以改

**Comment by 2823602869** [comment]
在麻烦一下，还有一个问题，登录后台会报这个错误
![image](https://github.com/user-attachments/assets/304f0582-8a3e-47cb-941e-73da1fe20897)
