### ISSUE TITLE
multilanguage support

### ISSUE THREAD

**Issue by rishi23root** [Innei/Shiro#51]
### Describe the bug

site is unable to render when using the default Chrome browser translate tool 

### Reproduction

site will give error on loading native english users 

### System Info

```Shell
idk
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
Thank you for your feedback
