### ISSUE TITLE
请求实现一些功能

### ISSUE THREAD

**Issue by MSDNicrosoft** [Innei/Shiro#56]
### Clear and concise description of the problem

能否实现以下功能：

#### 个人认为应该优先实现的：
- [x] ~~自定义 nav 菜单~~（Not planned）
- [ ] 更多预设或自定义社交图标的显示（如电子邮件，Telegram 等）(PR Welcome)
	- 个人认为有两种配置方式
		- 配置保存在后端，显示的社交图标通过请求后端 API 获取（但是目前似乎是在构建时获取）
		- ~~文档中给的后端的“云函数”的配置文件~~（Not realistic）

- [x] #66
- [x] ~~自定义版权协议~~（Not planned）

#### 个人认为可以在任何时候实现的
- [ ] 站点公告
- [x] ~~文章过期提醒（比如：`本文最后更新于 {days} 天前，其中的相关信息可能已经有所发展或是发生改变，请注意甄别。`）~~（Already impled）
- [x] 文章右侧 TOC 滚动跟随页面进度（Need help）
	- 个人认为，页面进度百分比应是固定的，而不是在 TOC 中可滚动
	![image](https://github.com/Innei/Shiro/assets/69967436/a50a8da4-2a12-4925-92b0-8452392a50d1)

#### 个人认为可选实现的
- [x] ~~自定义 footer/header（插入 HTML，CSS，JS）~~（Not planned）

### Suggested solution

~~我只是一个写后端的，前端的东西一概不知（除了懂一点 HTML 和 JS）。~~

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
1. 自定义 nav 菜单 
  
不在计划中，这部分逻辑基本不会改了，文案相关可以自己改，现在建议的方案也是建议 fork 本项目，然后定期与上游同步，在 vercel 部署，完全可以自己修改配置。header 的配置在 Header 底下的 config.ts

2. 更多预设或自定义社交图标的显示

PR Welcome

> Q: 文档中给的后端的“云函数”的配置文件
> A: 图标的获取在 云函数 不现实

3. 自定义文章排序方式

Planed.

4. 自定义版权协议

同第一点

5. 站点公告

Planed。但是是否有需要待商议，Kami 中有实现。

6. 文章过期提醒

本来就有

7. 文章右侧 TOC 滚动跟随页面进度

无法实现， Need help

8. 自定义 footer/header（插入 HTML，CSS，JS）

不做

**Comment by MSDNicrosoft** [comment]
> 1. 自定义 nav 菜单
> ...

了解了，谢谢。
已根据回复更新议题 Tasks

**Comment by Innei** [comment]
剩下两个目前没计划了
