### ISSUE TITLE
明亮模式下，表格中的文字颜色有问题

### ISSUE THREAD

**Issue by MSDNicrosoft** [Innei/Shiro#57]
### Describe the bug

问题如题（暗黑模式正常），症状如图：
![image](https://github.com/Innei/Shiro/assets/69967436/5e429c96-e8b1-42a8-b940-5e8725ed4a35)

暗黑模式下：
![image](https://github.com/Innei/Shiro/assets/69967436/b7069e2a-fb08-4453-800d-a551d746a1d0)

该段 Markdown：
```markdown
| 表达内容 | 示例 |
| - | - |
| 表示文件 | `options.txt` |
| 表示变量 | <版本名> |
| 在文件或文件夹末尾加上 `!` 表示 Minecraft 本体，分发这些文件违反了 [Minecraft Eula](https://account.mojang.com/documents/minecraft_eula) | libraries ! |
| 在文件或文件夹末尾加上 `*` 表示可删除，`**` 表示建议删除，`***` 表示必须删除 | libraries * |
```

### Reproduction

在文章中插入表格

### System Info

后端（注：非 Docker 环境，我的后端按照文档使用 Docker 部署）：

```text
  System:
    OS: Linux 5.4 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
    Memory: 4.92 GB / 15.62 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    pnpm: 8.6.11 - ~/.nvm/versions/node/v16.15.1/bin/pnpm
```

前端使用 Vercel（Node.js：`18.x`）。

访问时的浏览器所处环境：
```text
  System:
    OS: Windows 10 10.0.22621
    CPU: (4) x64 Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
    Memory: 2.95 GB / 7.89 GB
  Binaries:
    Node: 18.17.0 - F:\Develop\Nodejs\node.EXE
    Yarn: 1.22.19 - F:\Develop\Nodejs\yarn.CMD
    npm: 9.8.1 - F:\Develop\Nodejs\npm.CMD
    pnpm: 8.6.11 - F:\Develop\Nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2070.0), Chromium (115.0.1901.183)
```

用手机浏览器试了下，症状一样
手机浏览器：Kiwi Browser `116.0.5845.52`

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
Thank you for your feedback, fixed in latest version
