### ISSUE TITLE
请求支持 LaTeX

### ISSUE THREAD

**Issue by zhuozhiyongde** [Innei/Shiro#76]
如题，现在渲染博客内容并不支持 LaTeX，而这对于理工科学生是很重要的功能

**Comment by zhuozhiyongde** [comment]
用 Github Mobile 提请的 issue 好像没有提问模板功能的支持...抱歉

**Comment by Innei** [comment]
支持这种语法 $ c = \pm\sqrt{a^2 + b^2} $

**Comment by zhuozhiyongde** [comment]
原来是在$$之间还要再加一个空格啊... 之间用的都是直接 \$\lambda\$ 这样可以不加的（
