### ISSUE TITLE
请求 Shiro 实现一些功能 / 改进

### ISSUE THREAD

**Issue by zhuozhiyongde** [Innei/Shiro#79]
### Clear and concise description of the problem

以下是现阶段使用中遇到的一些问题，希望大佬能视情况更新：

* 博文不支持定时发布、草稿保存
* Markdown 代码块希望能够支持如 xLog 一样的高亮、渲染：现在的渲染方式会在内容过长时，层叠在代码上：
  ![image](https://github.com/Innei/Shiro/assets/36695271/775e1f1e-9de3-49c2-9d0c-c8d4e66e5119)
* 希望 Markdown 支持类似 xLog 一样的实时预览
* Github 代码块在网络不佳时无法正常显示，可以考虑配置国内的代理？
  ![image](https://github.com/Innei/Shiro/assets/36695271/15689d18-fd3e-4067-86b2-6616970e901f)

  

### Suggested solution

如题

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
1. 定时发送没计划，草稿保存做了
2. 高亮现在就有
3. 实时预览早就支持了，不懂你想说什么
4. GitHub 手动配 api token， 环境变量加一条 ：`GH_TOKEN=` 就行

所以，只有 `COPY` 遮挡的问题需要解决。

**Comment by zhuozhiyongde** [comment]
啊这 实时预览那个是我分错了 意思是后端写的时候左侧敲右侧看那个意思orz，不是前端Shiro的问题...

**Comment by Innei** [comment]
DONE

**Comment by zhuozhiyongde** [comment]
高亮那个...抱歉是我表述不清楚，当时看着觉得和xlog不太一样就提了一嘴没细想，实际上我刚才看了一下现在的渲染应该和xlog是一致的？我想了想应该想要表述的是：能给代码块加个底色圆角色块，然后字体是Fira Mono或者JetBrains Mono这种易读一些的？因为现在的花体我感觉有时候不太好看清楚，但这显然都是很个人化的请求，抱歉。
