### ISSUE TITLE
请求脚注显示优化

### ISSUE THREAD

**Issue by TNXG** [Innei/Shiro#84]
### Clear and concise description of the problem

- 当鼠标悬浮在正文`[^1]`生成的脚注标记上时，出现脚注部分内容

![image](https://github.com/Innei/Shiro/assets/69001561/c91755a5-afb8-4acf-9daa-229d48d89f22)

- 在页尾显示脚注详细内容的位置放置一个按钮以便快速返回正文

### Suggested solution

如题

### Alternative

Hexo中有类似的插件[kchen0x/hexo-reference](https://github.com/kchen0x/hexo-reference)，在下针对源内容进行了修改形成类如上图的效果[js](https://github.com/TNXG/blog/blob/master/themes/miracle/scripts/reference/lib/footnotes.js)、[css](https://github.com/TNXG/blog/blob/master/source/assets/css/float.css)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
PR welcome

**Comment by Innei** [comment]
Resolved in #129
