### ISSUE TITLE
后台已上传友链但没有显示

### ISSUE THREAD

**Issue by beiyaohhhc** [Innei/Shiro#90]
### Describe the bug

如图 后台已上传友链
![image](https://github.com/Innei/Shiro/assets/98569420/acf393b1-1be0-41dc-b875-066e0bda0b12)
但主页依然没有显示 也无申请按钮
![image](https://github.com/Innei/Shiro/assets/98569420/7f47f610-d7af-40c8-a769-ae482cdf31a0)
![image](https://github.com/Innei/Shiro/assets/98569420/ffb8c304-967f-4f49-8631-ca3b8479a444)
通过F12知道了是请求问题 
![image](https://github.com/Innei/Shiro/assets/98569420/df5c0e1d-888b-4d21-af5d-56c25a392551)
但请求的网址能正常访问
![image](https://github.com/Innei/Shiro/assets/98569420/cd1d6c40-c265-4bcf-8c76-79e8ee8d581a)

### Reproduction

无

### System Info

```Shell
后端
 System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (40) x64 Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz
    Memory: 46.16 GB / 62.49 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 12.22.9 - /usr/bin/node
    npm: 8.5.1 - /usr/bin/npm
前端： vercel
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
请求问题

**Comment by beiyaohhhc** [comment]
是否有解决办法 第一次用这个有点不懂![Screenshot_2023-09-26-12-50-34-515_com.microsoft.emmx.jpg](https://github.com/Innei/Shiro/assets/98569420/27b1c8e6-a8b1-4870-91be-35c97d4d26fb)

**Comment by renat3u** [comment]
同样的问题，检查了很多遍目录下的.env，在nginx修改了请求头，走cf代理的时候也修改了头，但都会遇到这个问题，束手无策了

**Comment by xtwgcyt** [comment]
情况和我完全一致，并且左上角的头像双击登录界面永远是”再试试哦“。F12显示api请求方式OPTIONS，结果404

**Comment by A233S** [comment]
同样的问题，请问有什么解决办法了吗？
