### ISSUE TITLE
miss gap between SVG and text when screen size is less than 768

### ISSUE THREAD

**Issue by LoTwT** [Innei/Shiro#94]
### Describe the bug

miss gap between SVG and text when screen size is less than 768

<img width="794" alt="image" src="https://github.com/Innei/Shiro/assets/50254496/4da8c057-fda6-40d7-8990-5a264c820706">

### Reproduction

https://innei.in/posts/programming/nestjs-with-trpc-and-dependency-injection

### System Info

```Shell
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 9.55 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.1 - ~/Library/Caches/fnm_multishells/1544_1695454330094/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 9.8.0 - ~/Library/Caches/fnm_multishells/1544_1695454330094/bin/npm
    pnpm: 8.7.6 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 17.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
Thank you for your report
