### ISSUE TITLE
文章内单独链接无法显示

### ISSUE THREAD

**Issue by baddate** [Innei/Shiro#96]
> cor使用docker部署，最新版本
> 前端主题是shiro，，最新版本，使用的vercel部署

问题：

markdown文章中的单独参考链接，预览的时候正常，但是发布后部分不显示，我测试的2个链接只显示GitHub网站的链接。

-----

复现：

测试内容
![image](https://github.com/mx-space/core/assets/37013819/4c6adf6d-a951-4f24-b368-9e406dead099)

预览界面
![image](https://github.com/mx-space/core/assets/37013819/2c5e8eb2-b584-49ae-a27c-255b28940a6e)

网站界面只显示GitHub的链接
![image](https://github.com/mx-space/core/assets/37013819/2993777a-f435-4ff3-8ef9-12c53884da9e)

**Comment by Innei** [comment]
Fix in ae062adb6c78a833dc80f45c12cf9f1d706aa1c1
