### ISSUE TITLE
部署完成，但是访问出现应用错误

### ISSUE THREAD

**Issue by wuhang2003** [Innei/Shiro#99]
![91ea56be27b0957f924f483ba3f7ebf3](https://github.com/Innei/Shiro/assets/108316419/81449221-0728-404a-a150-2da448c23182)

相关部署 log 中有一行红色 error 暂未确定是否与本问题相关

```log
Module not found: Can't resolve 'encoding' in '/vercel/path0/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib'
```

**Comment by Innei** [comment]
应该是你 `color` 配置错误，`light` 和 `dark` 要相同的长度

**Comment by wuhang2003** [comment]
fixed
